version: "3.9"

services:

    # Database - Mongo DB
    mongo:
        image: mongo:6.0.3
        container_name: mongo
        restart: always
        ports:
            - 27017:27017
        user: "${UID}:${GID}"
        volumes:
            - ./mongo-data/:/data/db/
            - ./mongo-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        environment:
            MONGO_INITDB_ROOT_USERNAME: aialbumadmin
            MONGO_INITDB_ROOT_PASSWORD: aialbumpw
            MONGO_INITDB_DATABASE: ai_album

    # Database Manager
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ADMINUSERNAME: aialbumadmin
            ME_CONFIG_MONGODB_ADMINPASSWORD: aialbumpw
            ME_CONFIG_MONGODB_URL: mongodb://aialbumadmin:aialbumpw@mongo:27017/
        links:
            - mongo


    # # AI Album server
    # al-album:
    #     build: ./server/ 
    #     hostname: ai-album
    #     restart: always
    #     container_name: ai-album